language: node_js
node_js:
  - "6.9.1"
  - "node"
services:
  - mongodb
install:
  - npm install
after_success:
  - mongo P4ngDb --eval "db.dropDatabase()"
  - npm run coveralls
notifications:
  slack:
      on_success: change
      on_failure: always
branches:
  only:
  - master
env:
  matrix:
  - TRAVIS_NODE_VERSION="6"

